[tool.ruff]
# which files/dirs to skip
exclude = [
    "external/",
    "third_party/",
    "vendor/",
]
line-length =  120
target-version = "py312"

[tool.ruff.isort]
lines-after-imports = 3

[tool.ruff.lint]
select = [
    "A",
    "ASYNC",
    "ARG",
    "B",
    "COM",
    "C4",
    "DJ",
    "DOC",
    "D",
    "E4", "E7", "E9",
    "EM",
    "F",
    "FA",
    "FAST",
    "FBT",
    "FLY",
    "G",
    "I",
    "ISC",
    "ICN",
    "LOG",
    "INP",
    "N",
    "PERF",
    "PD",
    "PLC", "PLE",
    "PT",
    "PTH",
    "Q",
    "RSE",
    "SIM",
    "SLOT",
    "YTT",
]

ignore = [
    "ARG002",
    "B007",
    "C408",
    "D103",
    "D100",
    "D102",
    "D105",
    "D107",
    "D202",
    "D205",
    "D417",
    "D413",
    "E303",
    "FA102",
    "F401",
    "INP001",
    "PD901",
]

[tool.ruff.per-file-ignores]
"tests/**/*.py" = ["D", "S101"]         # ignore docstring and security warnings in tests
"__init__.py" = ["F401"]                # allow unused imports in package inits
"scripts/*.py" = ["INP001", "ARG"]      # ignore input file & argument naming


[tool.mypy]
python_version = "3.12"
strict = true
ignore_missing_imports = true
disallow_untyped_defs = true
warn_unused_ignores = true